[package]
name = "preoomkiller"
version = "0.0.1"
authors = ["Michael Grosser <michael@grosser.it>"]

[dependencies]
getopts = "*"
regex = "*"
libc = "*"

[[bin]]
name = "preoomkiller"
path = "src/bin.rs"
